vich_uploader:
    db_driver: orm

    mappings:
       products:
           uri_prefix: '%app.path.products%'
           upload_destination: '%kernel.project_dir%/public%app.path.products%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
