#index:
#    path: /
#    controller: App\Controller\DefaultController::index
<<<<<<< HEAD
app_article_edit:
    path: /article/{id}/edit
    controller: App\Controller\ArticleController::edit
    methods: ['GET', 'POST']

app_back_article_show :
    path: /det/back/{id}
    controller: App\Controller\BackArticleController::showback
    methods : ['GET']

app_article_show:
    path: det/front/{id}
    controller: App\Controller\ArticleController::show
    methods: ['GET']

app_comment_new:
    path: '/new'
    controller: App\Controller\CommentController::new
    methods: ['GET', 'POST']


app_article_delete:
    path: /{id}
    controller: App\Controller\ArticleController::delete
    methods: ['POST']



    


   
=======
>>>>>>> Dev_masters-3A57/malek
